
services:
  
  taskmanagement.webui:
    image: taskmanagement.webui
    container_name: taskmanagement.webui
    build:
      context: .
      dockerfile: webui.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5078:80"
      - "7159:80"
    volumes:
      - dataprotection-keys:/home/app/.aspnet/DataProtection-Keys
      - ~/new-certs:/https
    depends_on:
      - taskmanagement.api
  taskmanagement.api:
    image:  taskmanagement.api
    container_name: taskmanagement.api
    build:
      context: .
      dockerfile: duende.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5241
      - ASPNETCORE_HTTPS_PORTS=7260
      - ConnectionStrings__DefaultConnection=Host=TaskManagement_DB;Database=TaskManagement;Username=postgres;Password=postgres
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password  
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5241:5241"
      - "7260:7260"
    volumes:
      - dataprotection-keys:/home/app/.aspnet/DataProtection-Keys
      - ~/new-certs:/https
    depends_on:
      - duendeserver
      
    
        
  duendeserver:
    image: duendeserver 
    container_name: duendeserver
    build:
      context: .
      dockerfile: duende.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__DefaultConnection=Host=TaskManagement_DB;Database=TaskManagement;Username=postgres;Password=postgres
      - ConnectionStrings__IdentityConnection=DataSource=IdentityServer.db
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5001:5001"
    volumes:
      - ~/new-certs:/https
    depends_on:
      TaskManagement_DB:
        condition: service_healthy
  TaskManagement_DB:
    image: postgres:latest
    restart: always
    container_name: TaskManagement_DB
    environment:
      POSTGRES_DB: TaskManagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  app_data:
  dataprotection-keys:
    
